name: API Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.yml'
      - '**.ini'
      - '**/README.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tests repo
        uses: actions/checkout@v4

      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          repository: Marco-03/task-manager-api
          path: backend_repo
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend_repo/backend/requirements.txt

      - name: Start backend
        run: |
          cd backend_repo/backend
          export TESTING=1
          nohup python app.py &>/tmp/backend.log &
          # Wait until port 5000 is ready
          for i in {1..20}; do
            if curl -sSf http://127.0.0.1:5000/ >/dev/null; then break; fi
            sleep 1
          done
          echo "==== Backend logs ===="
          cat /tmp/backend.log

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -v
